server:
  port: 8191
 
spring:  security:    user:      name: Sai      password: Marella  application:    name: OrderService
    
eureka:
  client:
    register-with-eureka: TRUE
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9190/eureka
  instance:
    hostname: localhost